- src/app/chat/components/ChatArea.tsx
- src/app/chat/components/ChatContent.tsx
- src/app/chat/components/ChatHeader.tsx
- src/app/chat/components/ChatInterface.tsx
- src/app/chat/components/ChatPageContent.tsx
- src/app/chat/components/CurrentChatInterface.tsx
- src/app/chat/components/EmptyState.tsx
- src/app/chat/components/MessageList.tsx
- src/app/chat/components/SuggestionChips.tsx
- src/app/chat/components/types.tsx
- 기존에 분리되어 있던 `NewChatInterface`, `DefaultChatInterface`, `ChatInterface` 등의 컴포넌트를 하나로 통합하여 모드별(chat mode: 기존, 신규 워크플로우, 일반 채팅) 렌더링을 간소화했습니다.
- 채팅 모드별 UI 로직을 명확하게 분리하고, 코드 중복을 제거하여 유지보수성을 향상시켰습니다.
- 채팅 헤더와 채팅 영역을 분리하여 역할을 분명히 하였고, 커스텀 컴포넌트(`ChatArea`, `ChatHeader`, `MessageList`, `EmptyState`, `SuggestionChips`)를 도입해 재사용성을 높였습니다.
- 기존 워크플로우 이력 불러오기 로직을 `mode` 상태를 기반으로 실행하도록 변경하여 로딩 및 에러 관리를 효율적으로 처리합니다.
- `ChatInterface` 컴포넌트를 모든 채팅 모드를 지원하도록 수정하고, 모드별 렌더링 분기를 추가함.
- `ChatContent` 컴포넌트 내 기존, 신규 워크플로우, 기본 채팅 모드 구분 로직을 `mode` 상태 관리로 변경 및 간소화.
- 채팅 헤더 UI를 별도 컴포넌트 `ChatHeader`로 분리하여 모드별 타이틀, 부제목, 대화 수 표시 로직 구현.
- 채팅 메시지 영역을 `ChatArea` 컴포넌트로 분리하고, 모드별 메시지 및 빈 상태 처리 로직 통합.
- 이전에 각각 분리되어 있던 메시지 리스트, 빈 상태, 제안 칩 UI를 각각 `MessageList`, `EmptyState`, `SuggestionChips` 컴포넌트로 분리.
- 기존 채팅 이력 불러오기 …
> [리팩토링] 채팅 컴포넌트 통합 및 모드별 인터페이스 일원화

- src/app/chat/components/ChatArea.tsx
- src/app/chat/components/ChatInterface.tsx
- src/app/main/components/Settings.tsx
- 기존에는 'existing' 모드에서만 지원되던 채팅 로딩과 표시 기능을 'deploy' 모드에도 확장하기 위해 변경했습니다.
- 이 변경으로 'deploy' 모드 사용 시에도 기존 대화 기록 표시와 로딩 상태 처리가 정상 동작하여 사용자 경험이 향상됩니다.
- `ChatArea` 컴포넌트의 로딩 상태 처리 코드를 'deploy' 모드까지 적용하도록 수정
- `ChatArea` 컴포넌트에서 대화 기록이 없을 때 보여주는 EmptyState를 'deploy' 모드에도 확장
- `ChatInterface` 컴포넌트에서 기존 대화 기록을 불러오는 로직을 'deploy' 모드까지 적용하도록 변경
> [수정] Chat 모드에 'deploy' 적용 범위 확장

- src/app/main/assets/CompletedWorkflows.module.scss
- src/app/main/components/CompletedWorkflows.tsx
- CompletedWorkflows 컴포넌트 내 헤더 부분의 액션 버튼들이 좌측에 배치되어 있어 UI가 어색한 문제를 개선하기 위해 수정했습니다.
- 헤더 액션 영역을 오른쪽으로 정렬하여 사용자 인터페이스를 보다 직관적이고 깔끔하게 만들고자 합니다.
- CompletedWorkflows.module.scss에 margin-left: auto;와 margin-right: 0; 스타일 추가로 headerActions를 오른쪽으로 정렬
- CompletedWorkflows.tsx에서 불필요한 headerInfo 영역(제목, 설명 텍스트) 제거하여 헤더 레이아웃 간결화
> [스타일] CompletedWorkflows 헤더 액션을 오른쪽 정렬로 변경

- src/app/_common/components/PagesLayoutContent.tsx
- src/app/chat/components/ChatInterface.tsx
- src/app/main/assets/CompletedWorkflows.module.scss
- src/app/main/components/Documents.tsx
- 모달이 열릴 때 사용자 화면 경험을 개선하기 위해 사이드바가 자동으로 닫히고, 모달이 닫히면 다시 이전 상태대로 복원되도록 기능을 추가했습니다.
- 여러 컴포넌트에서 사이드바 열림 상태를 공유하고 제어할 수 있도록 React Context로 상태 관리를 분리하여 코드의 유지보수성과 재사용성을 높였습니다.
- 이를 통해 UI의 일관성과 사용자 편의성을 향상시키며, 모달과 사이드바가 충돌하는 문제를 해결했습니다.
- `PagesLayoutContent` 컴포넌트에 `SidebarContext` 생성 및 `useSidebar` 훅 추가로 사이드바 상태를 전역에서 관리할 수 있게 구현
- `ChatInterface`와 `Documents` 컴포넌트에서 `useSidebar` 훅을 활용하여 모달이 열렸을 때 사이드바가 자동으로 닫히고, 모달 종료 시 원래 상태로 복원되도록 `useEffect` 로직 추가
- `PagesLayoutContent` 내 기존의 사이드바 상태 관련 코드를 Context Provider로 감싸 상태 공유 범위 확장
- 일부 스타일 파일에서 레이아웃 관련 CSS 개선 (예: `CompletedWorkflows.module.scss`의 flexbox 레이아웃 추가)
> [기능] 모달 열림 시 사이드바 자동 토글 및 사이드바 컨텍스트 추가

- public/embed-test.html
- src/app/_common/components/PagesLayoutContent.tsx
- src/app/chat/components/ChatInterface.tsx
- src/app/chat/components/ChatPageContent.tsx
- src/app/main/components/Documents.tsx
- 기존 PagesLayout과 채팅 컴포넌트에서 페이지 이동 관리를 일관되게 하기 위해 내비게이션 제어 함수를 추가하였습니다.
- 이를 통해 URL 쿼리 파라미터 기반의 채팅 모드 전환과 메인 뷰 전환을 보다 명확하고 쉽게 처리할 수 있도록 개선하였습니다.
- 채팅 모드 변경 시 기존에 직접 `router.push` 또는 `router.replace`를 호출하던 방식을 `navigateToChatMode` 함수로 추상화하여 유지보수를 용이하게 합니다.
- `PagesLayoutContent` 컴포넌트에 `navigateToChatMode` 함수 추가 및 컨텍스트 확장
- 기존 `SidebarContext`를 `PagesLayoutContext`로 이름 변경 및 기능 확장 (내비게이션 기능 포함)
- `usePagesLayout` 훅 추가 및 기존 `useSidebar` 훅은 `usePagesLayout`을 재사용하도록 변경
- 채팅 및 메인 페이지 이동 시 직접 라우터를 조작하던 부분을 컨텍스트 내 `navigateToChatMode` 함수 호출로 변경
- `ChatInterface`에서 레이아웃 컨텍스트를 사용하여 사이드바 상태 관리 및 모달 표시 시 사이드바 동작을 제어하도록 수정
- `ChatPageContent` 컴포넌트 내 채팅 모드 변경 시 라우터를 직접 사용하는 대신 `navigateToChatMode` 함수 호출 적용
- `public/embed-test.html` 내 챗봇 임베드 스크립트의 API 호스트 주소 변경 (`localhost:3000` → `localhost:3001`)
> [기능] PagesLayout과 Chat 컴포넌트에 내비게이션 제어 기능 추가

- src/app/api/retrievalAPI.js
- Modified the regex in isValidCollectionName function to allow for any length between 3 to 63 characters, ensuring it matches the intended validation criteria.
> fix: Update regex for valid collection name in retrievalAPI

- src/app/(page)/model/page.tsx
- src/app/_common/components/PagesLayoutContent.tsx
- src/app/_common/components/Sidebar.tsx
- src/app/_common/components/sidebarConfig.ts
- src/app/config.js
- src/app/main/components/types.ts
- src/app/model/components/MetricsPageContent.tsx
- src/app/model/components/ModelPageContent.tsx
- 모델 관리 및 훈련 기능을 위해 새로운 사이드바 메뉴와 관련 페이지를 추가했습니다.
- 기존 메인 페이지 구조에 모델 관련 뷰를 포함시키고, 모델 훈련 상태 모니터링을 위한 Metrics 페이지를 iframe으로 내장하여 쉽게 확인할 수 있도록 했습니다.
- 이를 통해 사용자들이 모델 훈련 진행 상황과 평가를 보다 직관적으로 확인하고 접근할 수 있게 됩니다.
- `/model` 경로에 접근 가능한 새로운 페이지 `ModelPage` 및 `ModelPageContent` 컴포넌트 추가
- Metrics(모델 훈련 모니터링) 페이지를 iframe으로 동적 로드하는 `MetricsPageContent` 컴포넌트 구현
- 사이드바에 모델 훈련 관련 메뉴(모델 훈련, 훈련 모니터, 평가, 모델 허브) 추가 및 확장 토글 기능 구현
- 기존 사이드바 및 레이아웃 컴포넌트에 모델 훈련 관련 항목 로직 추가
- `sidebarConfig.ts`에 모델 훈련 메뉴 항목 및 ID 리스트, 클릭 핸들러(로컬스토리지 저장 포함) 추가
- 환경 변수로부터 metrics 서버 URL(`NEXT_PUBLIC_METRICS_HOST`)을 받아 `MetricsPageContent`에서 사용하도록 설정
> [기능] 모델 훈련 사이드바 및 페이지 추가

- src/app/chat/components/ChatInterface.tsx
- 기존에 복잡하게 얽혀있던 채팅 초기화 로직을 간소화하고, 역할에 따라 useEffect를 분리했습니다.
- 이로 인해 초기 메시지 실행과 기존 채팅 데이터 로드가 명확히 분리되어 가독성과 유지보수성을 향상시켰습니다.
- 초기 메시지 실행 여부와 기존 대화 기록 로드 조건을 명확하게 처리하지 못해 발생할 수 있는 문제를 해결합니다.
- 초기 메시지가 있을 경우 해당 메시지를 입력 상태에 설정하고 URL 쿼리에서 `initial_message` 파라미터를 제거하는 로직을 별도의 useEffect로 분리.
- 기존 채팅 데이터가 있을 때 대화 기록을 불러오고 워크플로우를 실행하는 로직을 mode와 existingChatData 의존성에 따라 수행하도록 단순화.
- 불필요한 비동기 함수 감싸기 제거 및 의존성 배열 최적화로 코드 간결화.
> [수정] ChatInterface 초기화 로직 간소화 및 분리

- src/app/model/assets/ModelPage.module.scss
- src/app/model/components/MetricsPageContent.tsx
Refactor MetricsPageContent to use scoped styles from a new ModelPage.module.scss file instead of inline styles. This change improves maintainability and consistency by applying flex layout, background, border radius, and shadow to the container, and setting responsive iframe styling with padding and transitions.
> feat: Style MetricsPageContent with CSS modules

- src/app/main/components/charts/ChartDashboard.tsx
Introduce a sliderValue state to control the log limit slider input with a 500ms debounce before updating the actual logLimit state. This improves performance by reducing frequent data fetches while the user adjusts the slider.
- Initialize sliderValue alongside logLimit and sync them on max count update
- Update logLimit only after user stops sliding for 500ms
- Bind slider input to sliderValue for immediate UI feedback without triggering data reloads on every change
> feat: Add debounced slider control for log limit in chart

- .github/workflows/deploy.yaml
Removed NEXT_PUBLIC_BACKEND_PORT from the deployment environment variables as it is no longer required for the application setup. This simplifies the deployment configuration and reduces potential confusion.
> chore: Remove unused backend port env variable from deploy workflow

- src/app/_common/utils/isStreamingWorkflow.ts
- src/app/canvas/page.tsx
- src/app/chat/components/ChatInterface.tsx
Updated isStreamingWorkflow to accept a workflow ID string instead of a Workflow object. Adjusted all calls accordingly to pass the workflow name as the identifier. This ensures proper loading and checking of workflow data for streaming workflows.
> fix: Correct isStreamingWorkflow parameter to use workflow ID

- src/app/_common/components/ChatParser.tsx
- src/app/_common/components/ChatParserMarkdown.tsx
- Add preprocessing step to clean up duplicate quotes (""" or "") in string fields within ChatParser.tsx and ChatParserMarkdown.tsx
- Move duplicate quote removal earlier in ChatParser.tsx to ensure proper order of transformations
- Improve consistency of quote handling to prevent parsing errors in JSON and markdown processing
> feat: Remove duplicate quotes in JSON and markdown parsing

- src/app/_common/components/ChatParser.tsx
- src/app/_common/components/ChatParserMarkdown.tsx
Add handling to replace triple closing braces `}}}` with double braces `}}` in both ChatParser and ChatParserMarkdown components. This prevents malformed patterns like `}}}]` and ensures consistent brace formatting during preprocessing of JSON strings and inline markdown with citations.
> fix: Correct triple closing braces in JSON and markdown parsing

- src/app/canvas/components/Node/components/parameters/specialized/SchemaProviderParameter.tsx
- src/app/canvas/components/Node/components/specialized/SchemaProviderNodeParameters.tsx
- src/app/canvas/components/SpecialNode/SchemaProviderNode.tsx
- SchemaProviderNode의 복잡한 파라미터 처리 로직을 개선하고, 파라미터 컴포넌트를 분리하여 재사용성과 유지보수성을 높이기 위해 리팩토링을 진행했습니다.
- 기존에 SchemaProviderNode 내에 직접 구현되어 있던 파라미터, 이름 편집, 추가/삭제, 설명 처리 로직을 별도의 컴포넌트와 커스텀 훅으로 분리하였고, 이벤트 핸들링과 UI 렌더링을 모듈화했습니다.
- 이를 통해 코드 중복과 복잡도를 줄이고, 특별 파라미터(**kwargs 형태)의 추가 및 삭제, 편집 기능을 명확하게 분리 처리할 수 있게 되었습니다.
- `SchemaProviderParameter` 컴포넌트 추가: 파라미터와 설명 파라미터를 함께 관리하는 UI 컴포넌트로 분리하여, 선택형 입력(select)과 텍스트 입력을 상황에 맞게 렌더링하도록 구현.
- `SchemaProviderNodeParameters` 컴포넌트 추가: SchemaProviderNode에서 사용하는 파라미터들을 기본/고급으로 분리하고, 파라미터 추가/삭제/이름 변경 로직을 전담하도록 분리.
- `SchemaProviderNode` 컴포넌트 리팩토링
- 내부 상태 관리를 커스텀 훅(`useNodeEditing`)으로 대체.
- 직접 구현하던 파라미터 렌더링 로직을 `SchemaProviderNodeParameters` 컴포넌트로 위임.
- 노드 이름 편집, 마우스 이벤트 핸들링, 포트 렌더링 등 UI와 행위 분리.
- 예측 모드(`isPredicted`) 및 관련 이벤트 처리 추가.
- 파라미터 편집 시 연관된 설명 파라미터 이름도 함께 변경 및 삭제 …
> [리팩토링] SchemaProviderNode 내부 파라미터 구조 및 컴포넌트 모듈화

- src/app/canvas/components/Node/index.tsx
- src/app/canvas/components/Node/utils/nodeUtils.ts
- src/app/canvas/components/SpecialNode/SchemaProviderNode.tsx
- Node 관련 컴포넌트에서 CSS 클래스 이름을 전달하는 방식을 개선하여 스타일 관리 일관성을 높이기 위해 리팩토링을 진행했습니다.
- 기존에는 클래스 이름들을 문자열로 직접 전달했으나, 이를 styles 객체를 사용하도록 변경하여 스타일링 유지보수 및 확장성을 개선했습니다.
- `getNodeContainerClasses` 함수의 인자를 문자열 기반 `baseClass`에서 스타일 객체인 `styles`로 변경함.
- `Node` 컴포넌트 내에서 `getNodeContainerClasses` 호출 시 기존의 단일 클래스명 대신 styles 객체를 전달하도록 수정.
- `SchemaProviderNode` 컴포넌트에서도 동일하게 스타일 객체를 전달하도록 변경하여 코드 일관성 확보.
- 이를 통해 선택(selected), 미리보기(preview), 예측(predicted) 상태에 따른 클래스 적용을 styles 객체 기반으로 처리하도록 개선.
> [리팩토링] Node 컴포넌트 및 SchemaProviderNode의 스타일 적용 방식 개선

- src/app/api/workflow/deploy.ts
- src/app/chat/assets/ChatInterface.module.scss
- src/app/chat/components/DeploymentModal.tsx
- src/app/chat/components/SoundInput/SoundInputModal.tsx
- src/app/chatbot/[chatId]/page.tsx
- 기존 배포 상태 조회 기능에 사용자별 상태 확인을 위한 user_id 지원을 추가했습니다.
- 배포 모달(DeploymentModal) 내에서 현재 배포 상태를 확인하고, 버튼 클릭으로 배포 상태를 토글할 수 있도록 하여 UI/UX를 개선했습니다.
- 이를 통해 워크플로우 배포 관리가 보다 직관적이고 사용자 맞춤형으로 변경됩니다.
- `getDeployStatus` API 함수에 선택적 `user_id` 파라미터 추가, 사용자 단위 배포 상태 조회 지원
- `DeploymentModal` 컴포넌트에 배포 상태를 표시하는 토글 버튼 추가
- 초기 렌더링 시 사용자 배포 상태를 API로부터 조회하여 버튼에 상태 반영
- 버튼 클릭 시 `toggleDeployStatus` API를 호출해 실시간으로 배포 상태 변경 가능
- SCSS에 토글 버튼과 배포 정보 영역 스타일 추가하여 UI 개선
- 독립 웹페이지 링크 영역 우측에 배포 상태 토글 버튼 배치
- `chatbot/[chatId]/page.tsx`에서 불필요한 배포 상태 관련 에러 처리 주석 및 의존성 정리
> [기능] 배포 상태 조회 시 사용자 ID 지원 및 배포 상태 토글 기능 추가

- src/app/_common/api/workflow/workflowAPI.js
- src/app/canvas/assets/Canvas.module.scss
- src/app/canvas/assets/Header.module.scss
- src/app/canvas/components/Canvas/hooks/useKeyboardHandlers.ts
- src/app/canvas/components/Header.tsx
- src/app/canvas/page.tsx
- src/app/main/workflowSection/assets/CompletedWorkflows.module.scss
- src/app/main/workflowSection/components/CompletedWorkflows.tsx
- src/app/main/workflowSection/components/workflows/WorkflowEditModal.tsx
This pull request introduces enhancements to workflow sharing and editing permissions, improves the user interface for shared workflows, and refines keyboard handling and workflow saving logic. The main focus is on enabling granular sharing permissions (read-only vs. read-write), visually indicating workflow ownership, and ensuring that only authorized users can edit shared workflows. Additional improvements include UI tweaks for grid appearance and keyboard shortcut handling.
**Workflow sharing and permissions:**
* Added a `share_permissions` field (with options like "read" and "read_write") to workflows, allowing owners to specify whether shared users can edit or only view the workflow. The sharing modal now allows setting these permissions, and this information is saved and loaded with …
> fix: workflow sharing

- next.config.ts
Extend the experimental proxyTimeout setting to 600 seconds to allow longer backend response times, improving stability for slow or long-running requests.
> chore: increase proxy timeout in Next.js config

- src/app/admin/components/workflows/AdminUserTokenDashboard.tsx
This pull request makes a small update to the logic for displaying the details button in the `AdminUserTokenDashboard` component. The button will now appear if there is at least one workflow usage, rather than requiring more than one.
* Changed the condition to show the details button when `user.workflow_usage` has at least one entry, instead of more than one, in `AdminUserTokenDashboard.tsx`.
> fix: Update condition to display workflow usage details button
